---
- name: Check Prérequis Avant Upgarde AWX
  hosts: all
  become: yes
  tasks:
    - name: Alerte !
      fail:
        msg:
          - "La configuration matérielle du serveur ne correspond pas au minimum requis ! DcMcIx.net"
          - "Votre configuration actuelle :"
          - "OS : {{ansible_os_family}}" 
      when: ansible_distribution != "Debian"

- name: Upgrade AWX
  hosts: all
  become: yes
  tasks:
    - name: Include AWX Roles
      include_role: 
        name: awx_upgrade_single_node_k3s_v2
      when: ansible_distribution == "Debian"